name: recipe_app
description: "A new Flutter project."
publish_to: 'none' #

version: 1.0.0+1

environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter

  # Icon
  cupertino_icons: ^1.0.8
  font_awesome_flutter: ^10.8.0

  # Firebase
  firebase_core: ^3.15.2
  firebase_auth: ^5.7.0
  cloud_firestore: ^5.6.12
  firebase_storage: ^12.4.10
  firebase_crashlytics: ^4.3.10
  firebase_analytics: ^11.6.0
  firebase_performance: ^0.10.1+10

  # Auth
  google_sign_in: ^6.3.0
  flutter_facebook_auth: ^7.1.2
  email_validator: ^3.0.0

  # State management
  get: ^4.7.2
  shared_preferences: ^2.5.3

  # Image
  cached_network_image: ^3.4.1
  flutter_svg: ^2.2.0

  # Pop up
  flutter_popup: ^3.3.9
  awesome_snackbar_content: ^0.1.7
  giffy_dialog: ^2.3.0

  # Font
  google_fonts: ^6.2.1

  # Responsive
  flutter_screenutil: ^5.9.3

  # Functionality
  flutter_staggered_grid_view: ^0.7.0
  youtube_player_flutter: ^9.1.1
  dio: ^5.8.0+1
  shimmer_animation: ^2.2.2
  logger: ^2.6.1
  readmore: ^3.0.0
  timezone: ^0.10.1
  flutter_timezone: ^4.1.1
  url_launcher: ^6.3.2
  flutter_markdown_plus: ^1.0.3
  uuid: ^4.5.1

  # Notification
  flutter_local_notifications: ^19.3.1

  # AI
  flutter_ai_toolkit: ^0.9.2
  firebase_ai: ^2.2.1
  google_generative_ai: ^0.4.3

  # Permission
  permission_handler: ^12.0.1
  split_view: ^3.2.1


dev_dependencies:
  build_runner:
  flutter_gen_runner:

  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0
  change_app_package_name: ^1.5.0

flutter_gen:
  output: lib/gen/ # Optional (default: lib/gen/)
  line_length: 80 # Optional (default: 80)

  # Optional
  integrations:
    image: true
    flutter_svg: true
    rive: true
    lottie: true
# The following section is specific to Flutter packages.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/
    - assets/icons/
    - assets/translations/

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/to/resolution-aware-images

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/to/asset-from-package

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/to/font-from-package
