// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyClbiQ15Bi8Ef639wk9eM3syvlhpB_D3pA',
    appId: '1:672245011301:android:10b7d32ca839827f50878c',
    messagingSenderId: '672245011301',
    projectId: 'chefkiss-8258f',
    storageBucket: 'chefkiss-8258f.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBRKVCTytRNRQqSn7us9UntuujH7-RPXbU',
    appId: '1:672245011301:ios:672058d8c72d87b950878c',
    messagingSenderId: '672245011301',
    projectId: 'chefkiss-8258f',
    storageBucket: 'chefkiss-8258f.firebasestorage.app',
    androidClientId: '672245011301-oh3r11ckcohnd40ircimt2rov6poup6k.apps.googleusercontent.com',
    iosClientId: '672245011301-66ddlnjn2s70i0tui8ipspahoj7vucb5.apps.googleusercontent.com',
    iosBundleId: 'com.ephraim.sule.chefKiss',
  );

}