// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBoIR-x2cwTvzbMt2l_WChSTNOsHYHnoNg',
    appId: '1:312088988951:android:7b277723c945aa42aebb52',
    messagingSenderId: '312088988951',
    projectId: 'recipe-app-39f9f',
    storageBucket: 'recipe-app-39f9f.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBhBxBjg85NCscIEHcqkHoA8VVQHHs_S4A',
    appId: '1:312088988951:ios:ca348881275d0ed7aebb52',
    messagingSenderId: '312088988951',
    projectId: 'recipe-app-39f9f',
    storageBucket: 'recipe-app-39f9f.firebasestorage.app',
    androidClientId: '312088988951-e97lfikg7g7h0ml0sbc7dphnehv27qv3.apps.googleusercontent.com',
    iosClientId: '312088988951-30bugsq1tb0r9eam4b1kt4uc68jq45up.apps.googleusercontent.com',
    iosBundleId: 'com.ephraim.sule.chefKiss',
  );

}